import SidebarWrapper from "@/components/main/SidebarWrapper";
import { getAuthSession } from "@/lib/auth";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { cookies } from "next/headers";
import { redirect } from "next/navigation";
import "@/styles/globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const accounts = {
  label: "Alicia Koch",
  email: "alicia@example.com",
  icon: (
    <svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
      <title>Vercel</title>
      <path d="M24 22.525H0l12-21.05 12 21.05z" fill="currentColor" />
    </svg>
  ),
}

export default async function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getAuthSession()
  const layout = cookies().get("react-resizable-panels:layout")
  const collapsed = cookies().get("react-resizable-panels:collapsed")

  const defaultLayout = layout ? JSON.parse(layout.value) : undefined
  const defaultCollapsed = collapsed ? JSON.parse(collapsed.value) : undefined

  if (!session?.user) {
    redirect("/")
  }

  return (
    <main className="">
      <div className="min-h-screen">
        <SidebarWrapper 
          userEmail={session?.user.email}
          userImg={session?.user.image}
          defaultLayout={defaultLayout}
          defaultCollapsed={defaultCollapsed}
          navCollapsedSize={4}
        >
          {children}
        </SidebarWrapper>
      </div>
    </main>
  );
}